name: Deploy VitePress site to Pages

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  ️
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Site
        run: npm run docs:build